name: uts_nofri_sumalenda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  http: ^1.1.0
  intl: ^0.19.0
  google_nav_bar: ^5.0.6
  bot_toast: ^4.1.3
  fl_chart: ^0.65.0
  flutter_svg: ^2.0.8
  persistent_bottom_nav_bar: ^5.0.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.1
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  convex_bottom_bar: ^3.2.0
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/